name: NineIsBetterThanOne
main: MCPH\NIBTO\Main
author: [MinecrafterPH (fork), Gamecrafter, HellBublz (original)]
version: INDEV
api: 1.12.0
description: Disables death by explosions.
website: http://www.minecrafterph.tk
